### ISSUE TITLE
makefiles have hardcoded absolute paths in them

### ISSUE THREAD

**Issue by oboroc** [SuperIlu/lib16#1]
Hi @SuperIlu, I would like to build your lib16 examples (prj01/02/03), but can't figure out how.

wmake is not working, because I think it expects lib16 files to be under E:\_DEVEL\dos16bit and OpenWatcom to be under E:\WATCOM.

I wonder if it's possible to change all paths that start with E:\_DEVEL\dos16bit with something like ..\lib, and change -i="E:\WATCOM/h;..\lib" to something like -i="%WATCOM%/h;..\lib" or even -i="%INCLUDE%;..\lib"

I'm not experienced enough with dos and watcom to make those myself.

Or if all of this is too much trouble, please zip up your compiled binaries for prj01/02/03 and publish it as a release.

Thank you!

**Comment by SuperIlu** [comment]
hey @oboroc,

I'm not a watcom expert myself, I just created a project file using the IDE gui app and that created the makefile.
have you tried opening the project with the gui?

I can surely make a ZIP of the compiled binaries, but I can't promise you when I'll manage. So the above way might be faster (if it works)...

**Comment by oboroc** [comment]
I'll try to make a makefile that uses relative paths and let you know how it goes.

Do you know of any other game/graphics/sound projects for 16-bit DOS using OpenWatcom C/C++ 1.9 or Watcom C/C++ 10/11?

**Comment by oboroc** [comment]
Do you know if `#pragma aux` is the only way to do inline assembly in Watcom (https://users.pja.edu.pl/~jms/qnx/help/watcom/compiler-tools/cpasm.html)?

Also, do you have an example of implementing a fuction in name.asm file and linking it with Watcom DOS-16 project? I think I should be able to find some examples if I download OpenWatcom 1.9 source code, may be.

**Comment by SuperIlu** [comment]
No, sorry, can't really help you with that. As I said, I'm not really a Watcom expert. Most of my projects are compiled using DJGPP.

You can join the "DOS Shareware Zone" Discord and ask in the #game-dev channel: https://discordapp.com/invite/4NwSwA6
Or the "RetroDev" Discord: https://discord.gg/Js3uUrc
